language: python
python:
  - "2.6"
  - "2.7"
install:
  - pip install coverage==3.5.1
  - pip install https://github.com/paulocheque/python-qassertions/tarball/master
  - pip install --quiet -e .
script:
  - python runtests.py
